---
title: "Vasafeðgar"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
resource_files:
- auth/httr-oauth_rognvaldur
- auth/httr-oauth_kari
- auth/httr-oauth_solvi
- auth/httr-oauth_saemundur
---

```{r global, include=FALSE}
library(ggplot2)
library(lubridate)
library(plotly)
source('account_info.R')
source('utils.R')
```

```{r}
#for plots
icelandic_months <- function(x) {
    # months <- c("janúar", "febrúar", "mars", "apríl", "maí", "júní", 
    #             "júlí", "ágúst", "september", "október", "nóvember", "desember")
    months <- c("jan", "feb", "mars", "apr", "maí", "jún", 
            "júl", "ág", "sept", "okt", "nóv", "des")
    
    #paste0(mday(x), ". ", months[month(x)])
    months[month(x)]
}

icelandic_dates <- function(x) {
    months <- c("jan", "feb", "mars", "apr", "maí", "jún", 
                "júl", "ág", "sept", "okt", "nóv", "des")
    
    paste0(mday(x), ".", months[month(x)])
}
cols <- c('#BC3C29FF','#0072B5FF','#E18727FF','#20854EFF')
```

```{r}
start_date <- as.Date('2022-09-05')
vasa_date <- as.Date('2023-03-05')
weeks <- difftime(vasa_date,start_date,unit='weeks')
lag <- 14
```

```{r}
con <- dbConnect(MariaDB(), dbname = database_name, host = mysql$host,
                  port = mysql$port, user = mysql$user,
                  password = mysql$password,ssl.ca='cert.pem')
users <- arrange(load_data(con,'User'),name)
# activities <- update_activities(con,users) %>%
#               mutate(type=ifelse(type=='Golf','Walk',type)) #hack to allow golf activities
activities <- load_data(con,'Activity') %>%
              mutate(type=ifelse(type=='Golf','Walk',type)) #hack to allow golf activities
activity_types <- arrange(load_data(con,'ActivityType'),name)
activity_prop <- arrange(load_data(con,'ActivityProp'),athlete_id,activity_type)

```

Þolþjálfun {data-icon="fa-heart"}
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------


```{r}
radio_choices <- users$athlete_id
names(radio_choices) <- users$name
radioButtons(inputId = 'athlete_id',label='Íþróttamaður',choices=radio_choices,selected = radio_choices[1])
textInput('target_dist',label='Markmið (km)',value=500)
sliderInput('NordicSki',label='Gönguskíði',min=0,max=1,value = 0.2)
sliderInput('Ride','Hjól',min=0,max=1,value = 0.2)
sliderInput('Run',label='Hlaup',min=0,max=1,value = 0.2)
sliderInput('Swim','Sund',min=0,max=1,value = 0.2)
sliderInput('Walk','Ganga',min=0,max=1,value = 0.2)
actionButton('update',label='Uppfæra')
```

```{r}
reactive_vals <- reactiveValues(activity_prop=activity_prop,users=users)

observeEvent(input$athlete_id,{
    activity_prop_athlete <- filter(reactive_vals$activity_prop,athlete_id==input$athlete_id)
    if(nrow(activity_prop_athlete)==0){
        p <- rep(1/nrow(activity_types),nrow(activity_types)) #if no distribution yet, use default
    }else{
        activity_prop_athlete <- inner_join(activity_types,activity_prop_athlete,by=c('name'='activity_type'))
        p <- activity_prop_athlete$p
    }
    for(i in 1:nrow(activity_types)){
        updateSliderInput(inputId=activity_types$name[i],value=p[i])
    }
    updateTextInput(inputId='target_dist',value=reactive_vals$users$target_dist[reactive_vals$users$athlete_id==input$athlete_id])
},ignoreInit = TRUE)
```


Row {data-height = 450}
-----------------------------------------------------------------------

```{r}
process_dat <- eventReactive(input$update,{
    #normalize slider probabiities
    p_user <- unname(sapply(activity_types$name,function(a) input[[a]]))
    p_norm <- p_user/sum(p_user)
    for(i in 1:nrow(activity_types)){
        updateSliderInput(inputId=activity_types$name[i],value=p_norm[i])
    }
    activity_prop_athlete <- mutate(activity_types,p=p_norm,athlete_id=as.integer(input$athlete_id)) %>%
                             rename(activity_type=name,activity_type_ice=name_ice)
    reactive_vals$activity_prop <- save_activity_prop(con,input$athlete_id,activity_prop_athlete,reactive_vals$activity_prop)
    reactive_vals$users <- save_target_dist(con,reactive_vals$users,input$athlete_id,input$target_dist)
    activities_athlete <- filter(activities,athlete_id==input$athlete_id)
    eff_km_dat <- inner_join(activities_athlete,activity_prop_athlete,by=c('type'='activity_type','athlete_id')) %>%
                  filter(date>=start_date) %>%
                  mutate(effective_km=weight*distance/1000,
                         distance_km=round(distance/1000,digits=1),
                         time_min=floor(time/60),
                         time_sec=round((time/60-time_min)*60)) %>%
                  group_by(athlete_id) %>%
                  mutate(cum_effective_km=cumsum(effective_km)) %>%
                  ungroup()
    
    pred_dat <- filter(eff_km_dat,date>=(Sys.Date()-lag)) %>%
                group_by(athlete_id) %>%
                summarise(avg_km=sum(effective_km)/min(lag,as.numeric(Sys.Date()-start_date)+1),current_effective_km=max(cum_effective_km)) %>%
                mutate(pred_dist=current_effective_km + avg_km*as.numeric(vasa_date-Sys.Date())) %>%
                pivot_longer(cols=c('current_effective_km','pred_dist')) %>%
                mutate(date=if_else(name=='current_effective_km',Sys.Date(),vasa_date))

    return(list('activity_prop_athlete'=activity_prop_athlete,'eff_km_dat'=eff_km_dat,'pred_dat'=pred_dat))
})
```


### <font size="5em">Dreifing æfinga</font> 
```{r}
renderPlot({
ggplot(process_dat()$activity_prop_athlete,aes(activity_type_ice,p*100)) +
geom_col(position='dodge',width=0.4,fill=cols[2]) +
xlab('') +
ylab('Hlutfall (%)') +
scale_y_continuous(limits=c(0,100),expand=c(0,0.2)) +
theme_classic() +
theme(
    plot.title=element_text(size=18,face="bold"),
    axis.title.x=element_text(size=18),
    axis.title.y=element_text(size=18),
    axis.text.x=element_text(size=18),
    axis.text.y=element_text(size=18)
)
}) %>% bindEvent(input$update)
```

### <font size="5em">Áætlað vikuplan</font>
```{r}
renderPlot({
    week_plan <- mutate(process_dat()$activity_prop_athlete,athlete_id=as.integer(input$athlete_id)) %>%
                 inner_join(filter(process_dat()$pred_dat,name=='current_effective_km'),by='athlete_id') %>%
                 mutate(km_left=as.numeric(input$target_dist)-value,
                        weeks_left=difftime(vasa_date,date,unit='weeks'),
                        avg_left=(p*km_left/weight)/as.numeric(weeks_left))
    plot_dat <- filter(process_dat()$eff_km_dat,date>=floor_date(ymd(Sys.Date()), "week", 1)) %>% 
                group_by(activity_type_ice) %>% 
                summarise(cum_km=sum(distance/1000)) %>%
                left_join(select(week_plan,activity_type_ice,avg_left),.,by='activity_type_ice') %>%
                mutate(cum_km=ifelse(is.na(cum_km),0,cum_km)) %>%
                pivot_longer(cols=c('avg_left','cum_km'),names_to='type',values_to='dist') %>%
                mutate(type_ice=ifelse(type=='avg_left','Áætlun','Lokið'))
    ggplot(plot_dat,aes(activity_type_ice,dist,fill=type_ice)) +
    geom_col(position='dodge',width=0.4) +
    geom_text(data=filter(plot_dat,type=='avg_left',dist!=0),aes(y = dist, label = round(dist,2)),size=5, vjust = -0.2, hjust = 0.75) +
    scale_fill_manual(values=c(cols[1],'grey'),name='') +
    scale_y_continuous(limits=c(0,max(plot_dat$dist)+5),expand=c(0,0)) +
    xlab('') +
    ylab('Meðalfjöldi kílómetra á viku') +
    theme_classic() +
    theme(
        plot.title=element_text(size=18,face="bold"),
        axis.title.x=element_text(size=18),
        axis.title.y=element_text(size=18),
        axis.text.x=element_text(size=18),
        axis.text.y=element_text(size=18),
        legend.title=element_text(size=18),
        legend.text = element_text(size=18)
    )
}) %>% bindEvent(input$update)
```


Row {data-height = 550}
-----------------------------------------------------------------------

### <font size="5em">Æfingaálag síðustu tveggja vikna</font>
```{r}
renderPlotly({
    plot_dat <- tibble(date=seq(ymd(start_date),ymd(Sys.Date()),by=1)) %>%
                left_join(mutate(process_dat()$eff_km_dat,date=ymd(as.Date(date))),by='date') %>%
                mutate(effective_km=ifelse(is.na(effective_km),0,effective_km)) %>%
                group_by(date) %>%
                summarise(has_activity=any(!is.na(athlete_id)),
                          effective_km=sum(effective_km),
                          `Lýsing`=paste0('</br></br>Tegund - ',paste(activity_type_ice,collapse=';'),
                                      '</br>Lengd - ',paste(paste0(distance_km,' km'),collapse=';'),
                                      '</br>Tími - ',paste(paste0(time_min,':',time_sec,' mín'),collapse=';'),
                                      '</br>Meðalpúls - ',paste(avg_heartrate,collapse=';'))) %>%
                ungroup() %>%
                mutate(rolling_avg=roll_avg(effective_km,k=lag)) %>%
                filter(date > (Sys.Date()-lag))
    p <- ggplot() +
        geom_line(data=plot_dat,aes(date,rolling_avg),col=cols[3]) +
        geom_point(data=filter(plot_dat,has_activity),aes(date,effective_km,label=`Lýsing`),size=4,col=cols[3]) +
        geom_abline(intercept=as.numeric(input$target_dist)/(as.numeric(weeks)*7),slope=0,linetype='dashed') +
        scale_x_date(breaks = '2 day',
                     labels = icelandic_dates,
                     expand = expansion(add = 0.3)) +
        scale_y_continuous(limits=c(0,NA),expand = expansion(add = 0.6)) +
        xlab('') +
        ylab('Kílómetrar') +
        theme_classic()+
        theme(
            plot.title=element_text(size=18,face="bold"),
            axis.title.x=element_text(size=18),
            axis.title.y=element_text(size=18),
            axis.text.x=element_text(size=18,angle=30),
            axis.text.y=element_text(size=18),
            legend.title=element_text(size=18),
            legend.text = element_text(size=18),
            plot.margin=unit(c(0,1,0,0),'cm')
    )
    ggplotly(p,tooltip='label')
}) %>% bindEvent(input$update)
```

### <font size="5em">Uppsafnaðir kílómetrar</font>
```{r}
renderPlotly({
    max_y <- max(as.numeric(input$target_dist),max(process_dat()$pred_dat$value,na.rm=F))
    plot_dat <- mutate(process_dat()$eff_km_dat,`Lýsing`=paste0('</br></br>Dagsetning - ',date,
                                                                '</br>Tegund - ',activity_type_ice,
                                                                '</br>Lengd - ',paste0(distance_km,' km'),
                                                                '</br>Tími - ',paste0(time_min,':',time_sec,' mín'),
                                                                '</br>Meðalpúls - ',avg_heartrate))
    p <-ggplot(data=plot_dat,aes(as.Date(date),cum_effective_km)) +
        geom_step(size=2,col=cols[4]) +
        geom_point(aes(label=`Lýsing`),size=4,col=cols[4]) +
        geom_line(data=process_dat()$pred_dat,aes(date,value),linetype='dashed',col=cols[4]) +
        geom_abline(intercept = as.numeric(input$target_dist),slope=0) +
        scale_x_date(breaks = '1 month',
                     limits=c(ymd(trunc(start_date,'month')),ymd(vasa_date)),
                     labels = icelandic_months,
                     expand = expansion(add = 0)) +
        scale_y_continuous(breaks=seq(0,max_y+50,by=100),limits=c(0,max_y+50)) +
        xlab('Mánuður') +
        ylab('Uppsafnaðir kílómetrar') +
        theme_classic()+
        theme(
            plot.title=element_text(size=18,face="bold"),
            axis.title.x=element_text(size=18),
            axis.title.y=element_text(size=18),
            axis.text.x=element_text(size=18),
            axis.text.y=element_text(size=18),
            legend.title=element_text(size=18),
            legend.text = element_text(size=18),
            plot.margin=unit(c(0,1,0,0),'cm')
        )
    ggplotly(p,tooltip='label')
}) %>% bindEvent(input$update)
```


Styrktarþjálfun {data-icon="fa-dumbbell"}
=======================================================================